{% set name = "bloptools" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bloptools-{{ version }}.tar.gz
  sha256: 62a2e301b4afb925851e0141b5aef9f07b37f0c2845e5b7524ccee07de6b68c5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatch-vcs
    - hatchling
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - bluesky
    - botorch
    - databroker
    - gpytorch
    - h5py
    - matplotlib-base
    - numpy
    - ophyd
    - ortools-python
    - pytables
    - pytorch
    - scipy

test:
  imports:
    # The list of imports is generated via the following command:
    #   $ cd <blop-repo>/src
    #   $ find blop -name "*.py" | grep -v tests | sed 's/.__init__.py//g' | sed 's/._version//g' | sed 's;/;.;g' | sed 's/\.py//g'| sort -u
    - blop
    - blop.agent
    - blop.bayesian
    - blop.bayesian.acquisition
    - blop.bayesian.acquisition.analytic
    - blop.bayesian.acquisition.monte_carlo
    - blop.bayesian.kernels
    - blop.bayesian.models
    - blop.de
    - blop.de.de_opt_utils
    - blop.de.de_optimization
    - blop.de.hardware_flyer
    - blop.digestion
    - blop.dofs
    - blop.objectives
    - blop.plans
    - blop.plotting
    - blop.utils
    - blop.utils.functions
    - blop.utils.prepare_re_env
  commands:
    # - pip check || echo "No problem"
    - pip check
  requires:
    - pip
    - area-detector-handlers
    - databroker =1.2.5
    - python {{ python_min }}

about:
  home: https://github.com/NSLS-II/blop
  summary: Beamline optimization with machine learning
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://nsls-ii.github.io/blop

extra:
  recipe-maintainers:
    - mrakitin
    - AbbyGi
    - thomaswmorris
    - conda-forge/event-model
